[package]
name = "rss-json"
group = "infinyon-labs"
version = "0.1.0"
apiVersion = "0.1.0"
description = "Converts RSS XML into JSON"
license = "Apache-2.0"
visibility = "public"

[[params]]
name = "input"
description = "input description"
